name: Gradle Publish

on:
  push:
    branches:
      - custom



jobs:
  build:
    name: Gradle publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Publish
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
        run: ./gradlew publish -PmavenUsername=${MAVEN_USERNAME} -PmavenPassword=${MAVEN_PASSWORD}